name: Deploy to cPanel via SSH

on:
  push:
    branches:
      - main  # Change to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: admin.uthix.com
          username: adminuithix
          key: "b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDxKmnNWv
W738+ZjFSnMi+xAAAAEAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQDJj13zXNkG
/leSIqzfonuBydWXDGCQfWKIUHAn1jKmhVVHXSY0mVw424OQaSXju3AHN/iM2yqytylp9V
hET22Tlqotd9RrEZNzV7ETl8unlpYpUxe6PrDPP1qIJ1mZRMAbISGw7LY43ItZ6azDWXSK
7r1y5CKp/QnIszpdkXAG4HgoUIbIpL6htLzo1+BqXYEg6XMW7Mdg0Js8jqg0FyNO/qtI3h
mhx6c+9T2lxcnTJcbH6kvgJiOs3TAiUMa9JSkjZ3nHHFa+qZ1a4GXmiwLMZPKIZP+EMqCP
l/DBFRer+8/xKUg4PeRS6FRDoLSbnIUl2CRKbohmLOcsO/LIHqa+vs0APV6eORAJknWjHW
fvuGtjw0MVdpIqO1iyJqTzA9HYdwBc5xi0xdBU49aTNUJiEzB6vqrTwL2PiflIU+6fr+0W
hO29DIkzsRL/iIuUZU65v/EJByiSyz2PEbLufAQItwVyZGGIZMiqbppEm+4bH+lTlqP3SP
/tR23Qog8XkUrDoIJ/LiVnUxwKQv6WvcHTExlkUXhynR4yb+qRpW/xavj63L1mINKSRR6R
uRjJ747ihxV0K7pyqICiirZ31P999yrV5lqLhDFT7X9Yl65sroM9452h05ZzyP0FS/EWTZ
vQP2oqz+a0UOsIOm4Ix9IKeiJZtXfD6OQTh+k4UlKjhQAAB0BYI0t9yqf0uoi66xOnOiQt
kONvn6XWUJs1FDYvGgJUCLBBS4HuCyh9zDwrDcBVAQldPIfuIrziz1V9Igo1g6atwogvt5
L/krl9g1+bzOqk3zvA2C15ESnZhleP4Nt2GBb0sbWf7Ge+5APjvklFXbn7J4B5/ZkD8DAe
HqRoRVX+UG+GktAtrSg4sbW7aTtlnLqPWHa04s+N0sbvYtJ7jWy3h95ZkZWd8xeP4nQIpU
Ee/Kx0293xH44cGBXZLSipJGIbWCMZlVaMU+ax2t94BruG0HAPCBioWwt0H654eLYAThtH
uq6oWiKGr7FsIQOLI5ZdF/JSfUBvxbKbmd1joHtX9ZRPPO4qcFijAzqVRGAcdQRQMJUsb3
nbS9JOiJ321M5c+W+kjA0S5GeAJj0CAzI/f7yJ3yWr0afK6bl4ztImq3X1gbRfsbdrfIkb
0VqepPH9toqkDN7wdiUXmrfbUcpa4NsuzvWLiS+maOw/PYYppBDpCRc1pi8gpSvZx3WjWc
kb5X9sP9q/5+17rOAAi9UefceKm8sTBuW6eXwZHa06UCq4VhQ5oy5yrikD0Wb1YpTJBXvB
dwhvldRB2lMoT7QQeiYqObduVLJgYpi3fn/9ChiotEbxXhvCzLId2AMVSMSR/gBPxSkvrG
/0tc3e3NgdmUTS4lQqa57DZaGILQBspwfL5IAY1NfUsGBeoWumOiURcZcyu6cMrUEFUiqs
9R324adNjoFnmHmvPWL2Y/jWXHrGA6eO9J8dPQSdDbdttAeyp3YvDK/Cqs7r4zdXBXKP/l
XHZJlyzTjA6rEonydCh9gwxclIqDouKjRDEdpBASFEC0JGhvK/yQNmLNe05am4XgFBUvqk
ieTlezTcEYCX88OogSmtHVs/OPmbHp0k2fzfNJ6StvKt8i0G8KboEFxGFJYX+QmSRjc4pA
sZawl8fBHiWXa2D1S8D8tiRQYx7K+c8B3y5QrkHtPeGMLXGgj0TswLe3meq4IR838mOnqD
UIxKw4E5IHtVfHh5qp1o9XfBn4P3GP/yfjZSOsSgTGif/+liG6BqTLbC+QBid7hcKXR/bc
Z3NFdP0sa7s1fIJlw9HKjzKnBjS9ssmBxdYkSFk5bM+OVm5LBKrHIFvbohkDn4eErtCWfG
ZJSADLmKW98RDf9XdYoH2dRxtFlMTpw+ZbB0Cd1tCHIKD5ANv4n7HWb85GH8DEC109I+y7
pTeCBiQadkGKw+q+jFWPPAj3r1wTuCY1t/ZMlD9nJ2hmBbfyf3CzLp7plGpbUdH8eBJfFG
yrhOTS++ZdYwIzHHfGuBOMTvGrx3i1wJJSdQvN4nZ8qse420Hh+zHHsJ6C+3wMKJrydtJ8
CbpQuLU6+TIHyA3UR69bFmF6sYRH/cvvqrDwRlX4UGcGuCXQfJfEwwYVuH8NjWD79KuU1+
4W/RffImT/EAytQN41/q4mNbeuIXJgt22yR+bemntCIBCWvBqTguaftIgX25guNpXrKd0+
BQzrCRT/d53apaQGX9NJrnjm5pCiS3iuFaytR8nTVe59EKLWS5OWr5o3sz0RdbnJLSeBrk
Rx1MoMthSnxPeM5NNb/YnAKfn4nUSTQCY7/K6qeShuV9rIomPP3t5DsCEW5mFdOOF+JC7s
fr9rfW7oIozobNKKYyRzdX0EArWn4hfPGK5AEqRo+V5tUOeTcTpAGaVAkFjZEN8MviLmvC
1y20Z+u3E0Yf/Pe3OitA7Cz/hcsp4/5zEGWP5fx4EHl6pXetlvD4A72KB+idV3QUmtLPXz
TzShPXjHiiYDjCphyP7jcYCqJ6D/y5bFwn1attO2htnXU/h+CfA9cowc6R2ZmZxoL+1HIO
NJ1a02jodAchCccf8WpHcrBkSlyXkYQSePC1hBT/NKj8nh25sfmLgLlX88RyImoYwmLsgl
eC6d6v75o6kU1BmgAa5M8i3K1cQNQHpxGjvp+Ic8ql7qgiX6OJte9dwrigQwIWNHg90d8t
I5eapnnOUsjZdJjtlZfDwoR9oEQdBXyGaZB9R4d2KiVyVS0//Mj7KTXLdQENCOKpwoBcEa
l0J69bdR+ezxw56CNMK+5aCDrauDhgvV7anG7lAoFBsNPT6HKZ4TyBBieeuJe/l8QnX+vy
FjhnYgsAXZihvR7/KdiG/T0XJQBpaPC/P++iDXFwo61vGtPJJON5AkxfrkWWjJLfcTPw7X
7UXUG915WpZkbtxDjFhwXd5kD4V/fwmxozc3TNJVNnHpcR5rlqYHnYLnF6yTdC5q/xZDBn
hlYXCXRHQV8gCGX+EZKymOsoAlxH4Gm6lvyCguF6rxMB9/DwixMCR3WKyey2l0n9ebzUnJ
1AUOJ5pt9/jCaQEq6OpUBoUbsAiBXQL6p/TqeCaHDGSsC0Nfj135b0nGYh0hluRf++jKR0
PjTXFyp/ZnG2rxDJeMf16r3Q8nJFy7/F04oP6eKqIu/8FKy/KMnYPNo3JwsDWRzRmzoikr
EKDg=="
          port: 22
          script: |
            cd /home/adminuithix/public_html/
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear
            php artisan storage:link
