name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      
      - name: Setup SSH Key with Passphrase
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.CPANEL_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            eval "$(ssh-agent -s)"
            sshpass -p "${{ secrets.CPANEL_SSH_PASSPHRASE }}" ssh-add ~/.ssh/id_rsa

      - name: Debug SSH Connection
        run: ssh -v -o StrictHostKeyChecking=no adminuithix@admin.uthix.com "echo Connected Successfully"

      - name: Deploy to cPanel
        run: |
          ssh -o StrictHostKeyChecking=no adminuithix@admin.uthix.com "cd public_html && git pull origin main"
