name: Deploy to cPanel via SSH

on:
  push:
    branches:
      - main  # Change to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: admin.uthix.com
          username: adminuithix
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: 22
          script: |
            cd /home/adminuithix/public_html/
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear
            php artisan storage:link
