name: Laravel CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Set up PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '8.1'
      #     extensions: mbstring, intl, bcmath
      #     ini-values: post_max_size=256M, upload_max_filesize=256M

      # - name: Install Composer Dependencies
      #   run: composer install --prefer-dist --no-interaction --optimize-autoloader

      # - name: Run Tests
      #   run: vendor/bin/phpunit

      # - name: Build Frontend Assets
      #   run: |
      #     npm install
      #     npm run prod

      - name: Start SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CPANEL_SSH_KEY }}
          ssh-passphrase: ${{ secrets.CPANEL_PASSPHRASE }}
    
      - name: Debug SSH Key
        run: |
          echo "${{ secrets.CPANEL_SSH_KEY }}" > debug_key
          file debug_key

      - name: Deploy to cPanel Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'
            cd /home/yourcpaneluser/public_html/yourproject
            # If using Git on the server:
            git pull origin main
            # Alternatively, if deploying a package, unzip and update files:
            # unzip deploy-package.zip -d /home/yourcpaneluser/public_html/yourproject
            composer install --prefer-dist --no-interaction --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
          EOF
